---
- name: Create EC2 Instance
  hosts: localhost
  connection: local
  gather_facts: false

  tasks:
    - name: Launch Ubuntu t3.micro
      amazon.aws.ec2_instance:
        region: "ap-south-1"
        name: my-ubuntu-server
        instance_type: t3.micro
        image_id: ami-07a00cf47dbbc844c   # Ubuntu 22.04 LTS (us-east-1)
        state: running
        wait: true
      register: ec2

    - name: Show instance details
      debug:
        msg:
          - "Instance ID : {{ ec2.instances[0].instance_id }}"
          - "Public IP   : {{ ec2.instances[0].public_ip_address | default('N/A') }}"
          
